#!/usr/bin/env python3
"""Embed the reviewed provisioning sources below EC2's raw 16KiB user-data limit."""
import argparse
import base64
import gzip
import io
from pathlib import Path
import tarfile
import textwrap

ROOT = Path(__file__).resolve().parent.parent
SOURCES = ("bootstrap-production.sh", "direct-ingress.py")
PARAMETERS = {
    "REGION": "AWS::Region", "ACCOUNT_ID": "AWS::AccountId",
    "APP_SECRET_ARN": "AppSecretArn", "DB_SECRET_ARN": "Database.MasterUserSecret.SecretArn",
    "DB_HOST": "Database.Endpoint.Address", "TEST_DB_SECRET_ARN": "TestingDatabase.MasterUserSecret.SecretArn",
    "TEST_DB_HOST": "TestingDatabase.Endpoint.Address", "BACKEND_IMAGE": "BackendImageUri",
    "DIRECT_NGINX": "DirectNginx", "PUBLIC_ENI": "PublicNetworkInterfaceId",
    "SCOPED_WEBHOOK_SECRET_ARN": "ScopedWebhookSecretArn", "TLS_ARCHIVE_BUCKET": "TlsArchiveBucket",
    "TLS_ARCHIVE_KEY": "TlsArchiveKey", "TLS_ARCHIVE_SHA256": "TlsArchiveSha256",
    "TLS_ARCHIVE_VERSION_ID": "TlsArchiveVersionId",
}


def script():
    archive = io.BytesIO()
    with tarfile.open(fileobj=archive, mode="w", format=tarfile.USTAR_FORMAT) as tar:
        for name in SOURCES:
            content = (ROOT / "deploy/aws" / name).read_bytes()
            info = tarfile.TarInfo(name)
            info.size, info.mode, info.mtime = len(content), 0o700, 0
            tar.addfile(info, io.BytesIO(content))
    compressed = io.BytesIO()
    with gzip.GzipFile(fileobj=compressed, mode="wb", mtime=0) as stream:
        stream.write(archive.getvalue())
    payload = "\n".join(textwrap.wrap(base64.b64encode(compressed.getvalue()).decode(), 100))
    values = "\n".join(f"export {key}='${{{value}}}'" for key, value in PARAMETERS.items())
    return f"""#!/bin/bash
# Generated by scripts/render-production-userdata.py; edit the readable sources.
set -euo pipefail
umask 077
{values}
install -d -m 0700 /opt/silicon-iam/provisioning
base64 --decode <<'BOOTSTRAP_ARCHIVE' | tar --extract --gzip --file=- --directory=/opt/silicon-iam/provisioning
{payload}
BOOTSTRAP_ARCHIVE
exec /bin/bash /opt/silicon-iam/provisioning/bootstrap-production.sh
"""


def render(template):
    start = template.index("          Fn::Base64: !Sub |\n", template.index("        UserData:"))
    start += len("          Fn::Base64: !Sub |\n")
    end = template.index("\n  AutoScalingGroup:", start)
    content = script()
    # Include headroom for longer resolved ARNs, RDS names and object keys.
    if len(content.encode()) > 14_000:
        raise ValueError("Provisioning payload leaves insufficient room below EC2's16KiB limit")
    return template[:start] + textwrap.indent(content, "            ") + template[end:]


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    path = ROOT / "deploy/aws/production.yaml"
    current = path.read_text()
    expected = render(current)
    if args.check:
        if current != expected:
            raise SystemExit("Generated provisioning payload is stale; run scripts/render-production-userdata.py")
    else:
        path.write_text(expected)
    print(f"Provisioning user-data template: {len(script().encode())} bytes before parameter resolution.")
