// Generated by ../build.py. Queries are read-only; runtime supplies authorization.
const SPEC = {
  "slug": "overview",
  "name": "IAM Overview",
  "subtitle": "Production signals at a glance",
  "scope": "Production \u00b7 last 24 hours \u00b7 all events, including health probes",
  "queries": {
    "sources": "SELECT record.source::String AS source, toInt32(count()) AS events, toInt32(countIf(record.context.level::String = 'ERROR')) AS errors, toInt32(countIf(record.context.level::String = 'WARN')) AS warnings, toFloat64(max(event_ts_ms)) AS last_seen_ms FROM siliconiam WHERE event_ts_ms >= toUnixTimestamp64Milli(now64()) - 86400000 AND record.environment::String = 'production' GROUP BY source ORDER BY events DESC",
    "trend": "SELECT toFloat64(intDiv(event_ts_ms, 3600000) * 3600000) AS at_ms, toInt32(count()) AS value FROM siliconiam WHERE event_ts_ms >= toUnixTimestamp64Milli(now64()) - 86400000 AND record.environment::String = 'production' GROUP BY at_ms ORDER BY at_ms"
  }
};
const TRACE_SQL = "SELECT toFloat64(event_ts_ms) AS at_ms, record.source::String AS source, record.event::String AS event,\nrecord.context.level::String AS level, record.context.method::String AS method, record.context.route::String AS route,\nrecord.context.status::Nullable(Int32) AS status, coalesce(record.context.latency_ms::Nullable(Float64), record.context.duration_ms::Nullable(Float64)) AS latency_ms, record.context.request_id::String AS request_id,\nrecord.context.stage::String AS stage, record.context.command::String AS command,\nrecord.context.success::Nullable(Bool) AS success, record.context.code::String AS code FROM siliconiam";
const TIME_SQL = "event_ts_ms >= toUnixTimestamp64Milli(now64()) - 86400000";

const sum = (rows, key) => rows.reduce((n, row) => n + (Number(row[key]) || 0), 0);
const card = (label, value, detail, tone = "neutral", unit = "") => ({ label, value: Number.isFinite(Number(value)) && value !== null ? Number(value) : null, detail, tone, unit });
const columns = (...items) => items.map(([key,label,kind = "text"]) => ({key,label,kind}));
const table = (id,title,note,columns,rows) => ({id,title,note,columns,rows});
function present(raw) {
  const data = { title: SPEC.name, subtitle: SPEC.subtitle, scope: SPEC.scope, generated_at: new Date().toISOString(), tables: [], trace_enabled: true };
  if (SPEC.slug === "overview") {
    const sources = raw.sources || [];
    const expected = ["iam-api", "iam-scoped-api", "iam-worker", "iam-web"];
    data.cards = [card("Recorded events",sum(sources,"events"),"Across production sources"),card("Reporting sources",sources.length,"Observed in this 24-hour range"),card("Error events",sum(sources,"errors"),"May share a request ID","danger"),card("Warning events",sum(sources,"warnings"),"Diagnostic warnings","warn")];
    data.services = expected.map(source => ({source,...(sources.find(row => row.source === source) || {events:0,errors:0,warnings:0,last_seen_ms:null})}));
    const start = Math.floor(Date.now()/3600000)*3600000-23*3600000;
    const byHour = new Map((raw.trend || []).map(row => [Number(row.at_ms),Number(row.value)]));
    data.chart = {title:"Event volume",note:"Hourly buckets · UTC · current hour is partial",points:Array.from({length:24},(_,i)=>({at_ms:start+i*3600000,value:byHour.get(start+i*3600000)||0}))};
    data.tables = [table("sources","All production sources","Last seen measures telemetry freshness, not service availability.",columns(["source","Source"],["events","Events","number"],["errors","Errors","number"],["warnings","Warnings","number"],["last_seen_ms","Last seen","time"]),sources)];
  }
  if (SPEC.slug === "requests") {
    const total = raw.totals?.[0] || {};
    data.cards = [card("App requests",total.requests||0,"Health probes excluded"),card("Client errors · 4xx",total.client_errors||0,"Includes expected refusals","warn"),card("Server errors · 5xx",total.server_errors||0,"Completed API requests","danger"),card("P95 latency",total.p95_ms,"Across all included requests","neutral","ms")];
    data.tables = [table("routes","Route performance","Top 50 routes by request volume. P95 is calculated per route.",columns(["source","Source"],["method","Method"],["route","Route"],["requests","Requests","number"],["client_errors","4xx","number"],["server_errors","5xx","number"],["avg_ms","Average","ms"],["p95_ms","P95","ms"]),raw.routes||[]),table("recent","Recent requests","Latest 45 completed requests; choose a request ID to inspect its trace.",columns(["at_ms","Recorded","time"],["source","Source"],["method","Method"],["route","Route"],["status","Status","status"],["latency_ms","Latency","ms"],["request_id","Request ID","trace"]),raw.recent||[])];
  }
  if (SPEC.slug === "diagnostics") {
    const total = raw.totals?.[0] || {};
    data.cards = [card("Error events",total.errors||0,"One request may emit several","danger"),card("Warning events",total.warnings||0,"Warnings retained for context","warn"),card("Failed operations",total.failed_operations||0,"Explicit success=false only","danger"),card("Worker stages",(raw.stages||[]).length,"Stages observed in this range")];
    data.tables = [table("issues","Recent diagnostic signals","Latest 45 warnings, errors, 5xx responses or explicit failures. Empty means none were recorded.",columns(["at_ms","Recorded","time"],["source","Source"],["level","Level"],["event","Callsite / event"],["status","Status","status"],["stage","Stage"],["request_id","Request ID","trace"]),raw.recent||[]),table("stages","Worker stage progress","Heartbeats are sampled once per minute. These counts are signals, not processed-job totals.",columns(["stage","Stage"],["events","Signals","number"],["failures","Failures","number"],["last_seen_ms","Last seen","time"]),raw.stages||[])];
  }
  if (SPEC.slug === "clients") {
    const activity = raw.activity || [];
    const count = (source,event) => sum(activity.filter(row => row.source === source && row.event === event),"events");
    data.cards = [card("Page views",count("iam-web","page_view"),"Browser-reported analytics"),card("CLI commands",count("iam-cli","command.completed"),"Completed invocations"),card("SDK requests",count("rust-client","request.completed"),"Native request outcomes"),card("Update attempts",count("iam-daemon","update.completed"),"Completed daemon checks")];
    data.tables = [table("pages","Browser pages","Page paths are sanitized. Sessions are browser sessions, not people; counts overlap across pages.",columns(["path","Page"],["environment","Environment"],["views","Views","number"],["sessions","Sessions","number"]),raw.pages||[]),table("activity","Events by client","Each row is a distinct source, environment and event. Started/completed events are separate.",columns(["source","Source"],["environment","Environment"],["event","Event"],["events","Count","number"],["last_seen_ms","Last seen","time"]),activity),table("native","Recent native activity","Latest 35 completed command, update and SDK events. No argument values are collected.",columns(["at_ms","Recorded","time"],["source","Source"],["event","Event"],["command","Command"],["route","Route"],["success","Success","boolean"],["latency_ms","Duration","ms"],["request_id","Request ID","trace"]),raw.recent||[])];
  }
  for (const section of data.tables) {
    section.rows_key = Object.keys(raw).find(key => raw[key] === section.rows) || section.id;
    delete section.rows;
  }
  data.raw = raw;
  const bytes = value => {let n=0;for(const c of JSON.stringify(value)){const p=c.codePointAt(0);n+=p<128?1:p<2048?2:p<65536?3:4;}return n;};
  while (bytes(data) > 60000) {
    const largest = Object.values(data.raw).filter(rows => Array.isArray(rows) && rows.length > 5).sort((a,b) => JSON.stringify(b).length-JSON.stringify(a).length)[0];
    if (!largest) throw new Error("Window state exceeds the display limit");
    largest.pop();data.rows_trimmed = true;
  }
  return data;
}
async function rebuild() {
  const raw = {};
  for (const [key, sql] of Object.entries(SPEC.queries)) raw[key] = await mission_control.query(sql);
  return present(raw);
}
const subscriptions = Object.fromEntries(Object.entries(SPEC.queries).map(([key,sql])=>[key,{
  triggers:[{table:"siliconiam"}],sql,mode:"snapshot",
  onTrigger:(json,rows)=>present({...json.raw,[key]:rows})
}]));
export default defineProcessor({
  init:()=>rebuild(),subscriptions,
  tools:{
    summary:{args:{},run:json=>({title:json.title,scope:json.scope,generated_at:json.generated_at,cards:json.cards})},
    trace_request:{args:{request_id:"string"},run:async(json,{request_id})=>{
      if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(request_id)) throw new Error("Enter a valid request UUID");
      return {request_id,rows:await mission_control.query(TRACE_SQL+" WHERE "+TIME_SQL+" AND record.context.request_id::String = '"+request_id+"' ORDER BY event_ts_ms ASC LIMIT 40")};
    }}}
});
